name: Test Jenkins Action

on:
  workflow_dispatch:


jobs:

  testaction:
    
    runs-on: ubuntu-latest
    
    steps:
      
      - id: testjenkinsaction
        uses: mickeygoussetorg/trigger-jenkins-job@v1
        with:
          jenkins-server: secrets.http://localhost:8080/
          jenkins-job: buildtrigger
          jenkins-username: secrets.trigger
          jenkins-pat: secrets.11b14a3d02cdc5a75b80fd44c9e9554686
          poll-time: 10
          timeout-value: 600
          verbose: false
