name: Test Jenkins Action

on:
  workflow_dispatch:


jobs:

  testaction:
    
    runs-on: windows-latest
    
    steps:
      
      - id: testjenkinsaction
        uses: mickeygoussetorg/trigger-jenkins-job@v1
        with:
          jenkins-server: http://localhost:8080/
          jenkins-job: Build-test_trigger
          jenkins-username: Test-trigger
          jenkins-pat: 117908777c6b77e4b6a0f9ee975a6c0396
          poll-time: 100
          timeout-value: 100
          verbose: true
