name: Test Jenkins Action

on:
  workflow_dispatch:


jobs:

  testaction:
    
    
    steps:
      
      - id: testjenkinsaction
        uses: mickeygoussetorg/trigger-jenkins-job@v1
        with:
          jenkins-server: secrets.172.16.10.186:8080
          jenkins-job: buildtrigger
          jenkins-username: secrets.trigger
          jenkins-pat: secrets. 116bfcb234693eed27b4bbc959cd25e9fb
          poll-time: 10
          timeout-value: 600
