name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: toptal/jenkins-job-trigger-action@master
      with:
        url: "http://localhost:8080/"
        user: "Test-trigger"
        token: 117908777c6b77e4b6a0f9ee975a6c0396
        job: "foobar"
